---
- name: Create new source in Automation Services Catalog
  hosts: localhost 
  become: false
  gather_facts: false

  vars:
    username: username
    password: password
    source_name: New-Tower

  tasks:

  - name: Create source
    uri:
      url: https://cloud.redhat.com//api/sources/v1.0/sources
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      method: POST
      headers: 
        accept: "application/json"
      body_format: json
      body:
        availability_status: available
        imported: string
        name: "{{ source_name }}"
        source_ref: string
        source_type_id: "3"
    register: createSource
    changed_when: "createSource.status == 201"
