---
- name: Create new source in Automation Services Catalog
  hosts: localhost 
  become: false
  gather_facts: false

  vars:
    username: 
    password: 
    source_name: testTower-1 
    tower_url: 

  tasks:

  - name: Create source
    uri:
      url: https://cloud.redhat.com//api/sources/v1.0/sources
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      method: POST
      headers: 
        accept: "application/json"
      body_format: json
      body:
        availability_status: available
        imported: string
        name: "{{ source_name }}"
        source_ref: string
        source_type_id: "3"
    register: createSource
    changed_when: "createSource.status == 201"
    failed_when:
      - "createSource.status == 401"
      - "createSource.status == 403"
      - "createSource.status == 500"

  - name: Get source
    uri:
      url: https://cloud.redhat.com//api/sources/v1.0/source_types/3/sources?limit=100&filter[name]={{ source_name | urlencode }}
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      method: GET
      headers: 
        accept: "application/json"
    register: source
    failed_when:
      - "source.status == 404"

  - name: dumb source var
    debug:
      var: source

  - name: Create application
    uri:
      url: https://cloud.redhat.com//api/sources/v1.0/applications
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      method: POST
      headers: 
        accept: "application/json"
      body_format: json
      body:
        availability_status: "available"
        availability_status_error: "string"
        source_id: "{{ source.json.data[0].id }}"
        application_type_id: "1"
    register: createApplication
    changed_when: "createApplication.status == 201"
    failed_when:
      - "createApplication.status == 401"
      - "createApplication.status == 403"
      - "createApplication.status == 500"

  - name: Create endpoint
    uri:
      url: https://cloud.redhat.com//api/sources/v1.0/endpoints
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      method: POST
      headers: 
        accept: "application/json"
      body_format: json
      body:
        host: "{{ tower_url }}"
        path: "/"
        port: "80"
        role: "ansible"
        scheme: "https"
        verify_ssl: false
        source_id: "{{ source.json.data[0].id }}"
    register: createEndpoint
    changed_when: "createEndpoint.status == 201"
    failed_when:
      - "createEndpoint.status == 401"
      - "createEndpoint.status == 403"
      - "createEndpoint.status == 500"

  - name: Get endpoint
    uri:
      url: https://cloud.redhat.com//api/sources/v1.0/endpoints?limit=5&filter[host]={{ tower_url }}
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      method: GET
      headers: 
        accept: "application/json"
    register: endpoint

  - name: Create authentication
    uri:
      url: https://cloud.redhat.com//api/sources/v1.0/authentications
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      method: POST
      headers: 
        accept: "application/json"
      body_format: json
      body:
        authtype: "username_password"
        name: "Tower Password"
        username: "{{ username }}"
        password: "{{ password }}"
        resource_type: "Endpoint"
        resource_id: "{{ endpoint.json.data[0].id }}"
    register: createAuthentication
    changed_when: "createAuthentication.status == 201"
    failed_when:
      - "createAuthentication.status == 401"
      - "createAuthentication.status == 403"
      - "createAuthentication.status == 500"
